from __future__ import annotations

from collections.abc import Sequence
from datetime import date
from typing import Protocol

from urlshort.domain.entities.click_event import ClickEvent
from urlshort.domain.entities.short_url import ShortUrl
from urlshort.domain.entities.url_stats import UrlStatsDaily
from urlshort.domain.entities.user import User
from urlshort.domain.value_objects.email import Email
from urlshort.domain.value_objects.slug import Slug


class UserRepository(Protocol):
    async def add(self, user: User) -> User: ...
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...


class ShortUrlRepository(Protocol):
    async def add(self, short_url: ShortUrl) -> ShortUrl: ...
    async def get_by_slug(self, slug: Slug) -> ShortUrl | None: ...
    async def get_by_id(self, url_id: int) -> ShortUrl | None: ...
    async def list_by_user(
        self, user_id: int, *, limit: int = 100, offset: int = 0
    ) -> Sequence[ShortUrl]: ...
    async def delete(self, url_id: int) -> None: ...
    async def increment_click_count(self, url_id: int) -> None: ...


class ClickEventRepository(Protocol):
    async def add(self, event: ClickEvent) -> ClickEvent: ...
    async def count_by_url(self, short_url_id: int) -> int: ...
    async def list_by_url(
        self, short_url_id: int, *, limit: int = 100, offset: int = 0
    ) -> Sequence[ClickEvent]: ...


class UrlStatsRepository(Protocol):
    async def upsert_many(self, stats: Sequence[UrlStatsDaily]) -> None: ...
    async def get_timeline(
        self, short_url_id: int, *, start: date, end: date
    ) -> Sequence[UrlStatsDaily]: ...
    async def get_breakdown(
        self, short_url_id: int, *, dimension: str, start: date, end: date
    ) -> Sequence[tuple[str, int]]: ...


class RefreshTokenRepository(Protocol):
    async def store(self, token: str, user_id: int, expires_at: date) -> None: ...
    async def get_user_id(self, token: str) -> int | None: ...
    async def revoke(self, token: str) -> None: ...
