"""initial schema

Revision ID: 39cea4eef57c
Revises:
Create Date: 2026-04-28 18:15:15.159789+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "39cea4eef57c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "short_urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("target", sa.String(length=2048), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_clicks", sa.Integer(), nullable=True),
        sa.Column("click_count", sa.Integer(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_short_urls_expires_at"), "short_urls", ["expires_at"], unique=False)
    op.create_index(op.f("ix_short_urls_slug"), "short_urls", ["slug"], unique=True)
    op.create_index(op.f("ix_short_urls_user_id"), "short_urls", ["user_id"], unique=False)
    op.create_table(
        "click_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_url_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("referrer", sa.String(length=500), nullable=True),
        sa.Column("referrer_host", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("browser", sa.String(length=64), nullable=True),
        sa.Column("os", sa.String(length=64), nullable=True),
        sa.Column("device_type", sa.String(length=16), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("country_name", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["short_url_id"], ["short_urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_click_events_country_code"), "click_events", ["country_code"], unique=False
    )
    op.create_index(
        op.f("ix_click_events_occurred_at"), "click_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_click_events_referrer_host"), "click_events", ["referrer_host"], unique=False
    )
    op.create_index(
        op.f("ix_click_events_short_url_id"), "click_events", ["short_url_id"], unique=False
    )
    op.create_index(op.f("ix_click_events_slug"), "click_events", ["slug"], unique=False)
    op.create_table(
        "url_stats_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_url_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("device_type", sa.String(length=16), nullable=True),
        sa.Column("referrer_host", sa.String(length=255), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["short_url_id"], ["short_urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "short_url_id",
            "day",
            "country_code",
            "device_type",
            "referrer_host",
            name="uq_stats_url_day_dim",
        ),
    )
    op.create_index(op.f("ix_url_stats_daily_day"), "url_stats_daily", ["day"], unique=False)
    op.create_index(
        op.f("ix_url_stats_daily_short_url_id"), "url_stats_daily", ["short_url_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_url_stats_daily_short_url_id"), table_name="url_stats_daily")
    op.drop_index(op.f("ix_url_stats_daily_day"), table_name="url_stats_daily")
    op.drop_table("url_stats_daily")
    op.drop_index(op.f("ix_click_events_slug"), table_name="click_events")
    op.drop_index(op.f("ix_click_events_short_url_id"), table_name="click_events")
    op.drop_index(op.f("ix_click_events_referrer_host"), table_name="click_events")
    op.drop_index(op.f("ix_click_events_occurred_at"), table_name="click_events")
    op.drop_index(op.f("ix_click_events_country_code"), table_name="click_events")
    op.drop_table("click_events")
    op.drop_index(op.f("ix_short_urls_user_id"), table_name="short_urls")
    op.drop_index(op.f("ix_short_urls_slug"), table_name="short_urls")
    op.drop_index(op.f("ix_short_urls_expires_at"), table_name="short_urls")
    op.drop_table("short_urls")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
